### ISSUE TITLE
Split the pulling of data over multiple timers ?

### ISSUE THREAD

**Issue by Trefex** [pszafer/home-assistant-bosch-custom-component#18]
Hi,

I read in the wiki that one should not add all sensors as it could “lock up” the KM module and create certain issues.

Could this avoided by only querying the KM module in small batches instead of checking all sensors every 1 minute. One could check 5 sensors after 1 minute, 5 sensors after 1:30 mins etc. Something like that.

Would it help?

**Comment by pszafer** [comment]
I tried it already, but I failed. I haven't had much time to test, but I couldn't make asyncio.Lock to "wait" to be ready.

But imagine:
- HC1, HC2, DHW1, DHW2 - every 30 secs in single call from HA. It takes about 30 secs to fetch all data. - let's call it `fetch1`
- Sensor1: every 60 secs - fetching takes about 5 secs - `fetch2`
- Sensor2: every 90 secs - fetching takes about 5 secs - `fetch3`

If `fetch1` is in progress and `fetch2` wants to be in progress then it should wait till `fetch1` finishes, but it abort instead.
if user change mode or do something then this call won't be blocked.
If I have one timer then at least I'm sure that there is maximum 2 simultaneous calls to gateway.
If I put more times then I can have multiple simultaneous calls and it might be worse than it is right now.

**Comment by Trefex** [comment]
Does something like this help at all?

https://www.artificialworlds.net/blog/2017/05/31/python-3-large-numbers-of-tasks-with-limited-concurrency/

I am not deep into HASS dev (barely touching the surface) as I just recently started.

**Comment by pszafer** [comment]
Maybe it's worth a try. I'll check it out

**Comment by pszafer** [comment]
Sorry, I don't know how to implement it in a way working with home assistant helpers. If you are willing to make PR, we can give it another shot.
