### ISSUE TITLE
Add support for setting room setpoint 

### ISSUE THREAD

**Issue by Brumhilde** [pszafer/home-assistant-bosch-custom-component#22]
**Is your feature request related to a problem? Please describe.**
I cannot set room temperature setpoint

**Describe the solution you'd like**
Set room temperature setpoint using "/heatingCircuits/hc1/temperatureRoomSetpoint"

**Additional context**
        {
            "id": "/heatingCircuits/hc1/temperatureRoomSetpoint",
            "maxValue": 30.0,
            "minValue": 5.0,
            "recordable": 0,
            "state": [
                {
                    "off": 0.0
                }
            ],
            "type": "floatValue",
            "unitOfMeasure": "C",
            "value": 22.0,
            "writeable": 1
        },

**Comment by pszafer** [comment]
Missing installation info.
Provide bosch_scan.
In what operation_mode this setpoint should be set?
In most cases in RC35 this URI doesn't work. You need to set `temperatureLevels/day` to set temperature.

**Comment by Brumhilde** [comment]
[rawscan.txt](https://github.com/pszafer/home-assistant-bosch-custom-component/files/4128227/rawscan.txt)

Attached the rawscan. I have it in operationMode manual.

**Comment by pszafer** [comment]
Anything about your installation?
What do you have inside? Heater, I see RC300, what else?

What's the trouble. I see RC300 in your setup, same firmware as everybody, but you have different operation modes for HC1 and DHW.

DHW have in my setup:
- ownprogram
- high
- Off
- HCprogram

And in yours:
- Off
- low
- high
- ownprogram
- eco

Anyway I will try to add those operation modes for you as well.

About HC1 - it should work. In manual mode it is sending temp to `/heatingCircuits/hc1/manualRoomSetpoint`.
Try to fetch some logs, so we can find out why HC1 is not working as expected.

**Comment by Brumhilde** [comment]
I have a Bosch air-to-water heat pump. I think it has a variant of the RC300 that is called HPC400 in Sweden and Norway.

https://www.bosch-climate.se/globalassets/content-images/dokumentbibliotek/handbocker/luftvatten/anvandarhandl_hpc400_600_6720820629_01.pdf

**Comment by Brumhilde** [comment]
I have verified setting room temperature with HC1 is ok with component version 0.7.0 and HA 0.105.0. Thanks!
