### ISSUE TITLE
Actual water temperature of Boiler

### ISSUE THREAD

**Issue by Railittle** [pszafer/home-assistant-bosch-custom-component#8]
Hi  pszafer,

As you ask me I attached my rawscan. Also the screenshot of my sensors.
They are not made on the same time. As you see there are two Invalid sensors in my config.

Thx for your support so far.

[bosch_scan.zip](https://github.com/pszafer/home-assistant-bosch-custom-component/files/3439706/bosch_scan.zip)
![hp29-7-2019](https://user-images.githubusercontent.com/41593683/62014822-254cfa00-b1a6-11e9-9f9a-60b174f3fa82.JPG)

**Comment by pszafer** [comment]
I see it.  Actually you don't have these sensors.
Right now you can just delete those. In next version I will just stop adding sensors if they are not exist.

**Comment by Railittle** [comment]
Hi Pszafer,

Can you explain how is it possible that these sensor are exest in my ProControl app? I guess that the data is available in the gateway, because it appairs in the app. Is it possible to add these in next version? Below all the info I can read from my heatpump. Its in Dutch, but under Warm water you see the actual hot water temperature. When it is not possible, then it stops and I will continue with other Home Assistant challenges :)

![Image-1](https://user-images.githubusercontent.com/41593683/62085712-86370980-b25c-11e9-94f3-89e9896b3148.jpg)
![Image-2](https://user-images.githubusercontent.com/41593683/62085716-8800cd00-b25c-11e9-8e25-dbd8b871cbb2.jpg)

**Comment by pszafer** [comment]
There is new version of component, which should cover your sensors.
Please test it. Closing issue for now. I'll reopen if you still have issue.
