### ISSUE TITLE
Move bosch into custom_components directory

### ISSUE THREAD

**Issue by leinich** [pszafer/home-assistant-bosch-custom-component#9]
Could you please move the bosch directory into custom_components?
This would allow to integrate this component via HACS and make updates easy.

**Comment by pszafer** [comment]
I will, but... not yet. As I have to implement sort of update mechanism of data which are in ~/.homeassistant/.storage.
I'm changing things there in each version... as I'm trying to implement one solution for different firmwares...

**Comment by pszafer** [comment]
I'm preparing to do what you asked.
So github repo shoudl look like this:
```
custom_components/bosch/FILES
```
am I right?

**Comment by leinich** [comment]
Yes you are right. 
This should be sufficient to be able to add it manually to hacs.

If you want to be listed in HACS default repository, there are more changes needed (see https://hacs.xyz/docs/publish/start ).

**Comment by pszafer** [comment]
I moved it to `custom_components`.
I don't want to be listed in HACS as my plan is to add this component to HA as standard integration in near future.
